# Generated by Django 5.2.11 on 2026-02-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=20)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("pe_ratio", models.FloatField(blank=True, null=True)),
                ("eps", models.FloatField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("intrinsic_value", models.FloatField(blank=True, null=True)),
                ("discount_level", models.FloatField(blank=True, null=True)),
                ("opportunity_score", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
    ]
